### PR TITLE
Update str::trim to properly handle non-ASCII characters on Windows

### PR DESCRIPTION
**Pull request by acwagen**

### CODE REVIEW

**Comment by jmrandol** [comment]
We probably need to include <cwctype> at the top

**Comment by acwagen** [comment]
@jmrandol I added wctype.h as an include.

**Comment by jmrandol** [comment]
Oh, does including cwctype (C++ style vs. C style wctype.h) not work?

**Comment by acwagen** [comment]
No, it doesn't, it can't find cwctype.h (on both Linux and Windows). The existing include was for ctype.h as well, not cctype.h.

**Comment by jmrandol** [comment]
Hmm, usually when you include `#include <cwctype>` without the .h extension C++ will find the right header file

**Comment by acwagen** [comment]
Should be good now!

**Pull request merged**
