### PR TITLE
Fix bug in creating __init__.py

### PR DESCRIPTION
**Pull request by JonathanMeans**
Fixes https://github.com/ngageoint/six-library/issues/43

### CODE REVIEW

**Comment by asylvest** [comment]
I'm a little confused... how does this change fix the problem?  I thought `tg.bld.install_files()` only ran if the file didn't exist in the installation directory (due to some internal checking magic waf did), so can you explain how adding this check makes waf not get confused?  If I recall correctly, the issue we were seeing amounted to that sometimes waf got in a bad state and didn't re-generate the file... my best guess was due to getting the same signature (see notes on #131) though I could have been wrong.

**Comment by JonathanMeans** [comment]
So the real problem was just above that, line 1461 in the latest commit. That line checks whether there's an __init__.py in the target directory, and all the installation stuff happened under that condition. So if you just removed the install dir, it would see the __init__.py still in target, and just not do anything. Removed the new check since it's redundant.

**Comment by asylvest** [comment]
Ahh - ok!  I was just looking at the diff and just seeing whitespace changes and thinking what the heck.  Thanks for the explanation - that and looking at the full file view made clear to me that yeah, while technically "just whitespace changes", they had the effect of taking that stuff out of the conditional block.

OK, this makes sense.

**Comment by asylvest** [comment]
FYI @chvink @clydestanfield

**Comment by asylvest** [comment]
FYI @apakanati @tolsonMDA as you may have run into this before too

**Pull request merged**
