### PR TITLE
Merge pull request #49 from mdaus/BufferView-section-and-cleanup

### PR DESCRIPTION
**Pull request by laian**
Changed comment style

### CODE REVIEW

**Comment by asylvest** [comment]
GitHub's showing no files changed..?

**Comment by laian** [comment]
I don't know... I pushed a new commit to the branch after you merged it originally but it's not seeing it?

**Comment by asylvest** [comment]
I deleted the branch after I merged it... maybe that confused GitHub?

**Comment by laian** [comment]
I think so.  I'm confused too, :confounded:

**Pull request merged**
