### PR TITLE
CMake build system

### PR DESCRIPTION
**Pull request by scolcord**
Add a CMake build system for coda-oss.  This system is orthogonal to the existing WAF build system, and should not affect it.

Please consult CMakeREADME.txt for implementation details.

While the initial development for this system was done on Windows, it then moved to Linux for work on the driver builds, and that work has not been retested on Windows, so the Windows builds are most likely broken at this point.

SWIG and Python support are also not yet supported.

### CODE REVIEW

**Comment by kdwilhelm** [comment]
At this point the CMake support is pretty much complete. There are a few things excluded (jasper driver for J2K; libxml and expat drivers for XML, though I'm not aware of anyone using these). The CMake build is documented in cmake/README.md and most of the common functions are in cmake/CodaBuild.cmake and cmake/CodaFindSystemDependencies.cmake.

All build targets are exported to `<install prefix>/lib/cmake/coda-ossTargets.cmake` and a wrapper `<install prefix>/lib/cmake/coda-ossConfig.cmake` is produced to import them into downstream projects. This greatly simplifies handling of dependencies, as consumers only need to include the wrapper file and specify their direct dependencies and CMake will handle linking transitive dependencies along with them.

A simple, preliminary Conan recipe is also included (though it does not expose all of the CMake options). Conan consumers of coda-oss can import the CMake targets using Conan's cmake_paths generator to help locate the coda-ossConfig.cmake wrapper.

**Comment by jmrandol** [comment]
@kdwilhelm I'll take a look at this soon by attempting a build.  For Conan, does it allow me to upload my build artifacts to Artifactory?

**Comment by kdwilhelm** [comment]
That's right, you can run the following to register your artifactory server:
```
# add a remote called "myartifactory" at address "http://localhost:8081/artifactory/api/conan/conan-local"
conan remote add myartifactory http://localhost:8081/artifactory/api/conan/conan-local
```

Then to build and upload the package:
```
# build package (run from project base directory)
conan create . user/testing

# upload the package (recipe and source only)
conan upload coda-oss/CMake_8d5d3d47de1ed523@user/testing -r myartifactory

# or, upload the package with 1 binary version, corresponding to the given hash
conan upload coda-oss/CMake_8d5d3d47de1ed523@user/testing:ce48025d3ea780f06fd33fb4edde6af3d962b05e  -r myartifactory

# or, upload the package with all binary versions in your local cache
conan upload coda-oss/CMake_8d5d3d47de1ed523@user/testing --all -r myartifactory
```

There is some more documentation here:
https://docs.conan.io/en/latest/uploading_packages/artifactory_ce.html#creating-and-using-a-conan-repo
https://docs.conan.io/en/latest/reference/commands/creator/upload.html

Currently the recipe is configured to dynamically generate the version as "{git branch name}_{first 16 characters of commit hash}", so for the current head of this branch it is "CMake_8d5d3d47de1ed523"

One issue on Windows is the 260 character path length limit in some Windows API calls. Conan generates some very long path lengths due to concatenating the package name, version, channel, and binary hash to set the build and package directories. This results in paths longer than 260 characters during the build, which a lot of Windows software is unable to handle. Conan has a workaround, which you can enable globally by uncommenting and setting the following in your ~/.conan/conan.conf file:
```
user_home_short = C:\Users\username\.conanshort
use_always_short_paths = True
```
Or you can set the environment variables `CONAN_USER_HOME_SHORT=[path]` and `CONAN_USE_ALWAYS_SHORT_PATHS=1`.

This will run the build in a subdirectory of the path you specify and create symbolic links to it from the normal location in conan's local cache.

Windows itself can handle longer paths if a certain registry key is enabled, and recent versions of Python and Conan should handle long paths as well, but I still got some CMake and MSVC (2015) errors with the long paths.

**Comment by jmrandol** [comment]
I was able to build with CMake fine.  When I try to build via Conan I get some issues on Windows 10:

```
Determining if the fseeko exist failed with the following output:
Change Dir: C:/Users/jrandolp/.conan/data/coda-oss/CMake_ae1a9d6d2c0f50a7/_/_/build/6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/MSBuild/15.0/Bin/MSBuild.exe cmTC_00521.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=15.0 /v:m
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework^M
Copyright (C) Microsoft Corporation. All rights reserved.^M
^M
  Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27027.1 for x64^M
  Copyright (C) Microsoft Corporation.  All rights reserved.^M
  ^M
  cl /c /Zi /W1 /WX- /diagnostics:classic /Od /Ob0 /D WIN32 /D _WINDOWS /D _FILE_OFFSET_BITS=64 /D _LARGEFILE_SOURCE /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_00521.dir\Debug\\" /Fd"cmTC_00521.dir\Debug\vc141.pdb" /Gd /TC /errorReport:queue "C:\Users\jrandolp\.conan\data\coda-oss\CMake_ae1a9d6d2c0f50a7\_\_\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\CMakeFiles\CMakeTmp\CheckSymbolExists.c"^M
  CheckSymbolExists.c^M
  ^M
C:\Users\jrandolp\.conan\data\coda-oss\CMake_ae1a9d6d2c0f50a7\_\_\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\CMakeFiles\CMakeTmp\CheckSymbolExists.c(8): error C2065: 'fseeko': undeclared identifier [C:\Users\jrandolp\.conan\data\coda-oss\CMake_ae1a9d6d2c0f50a7\_\_\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\CMakeFiles\CMakeTmp\cmTC_00521.vcxproj]^M

File C:/Users/jrandolp/.conan/data/coda-oss/CMake_ae1a9d6d2c0f50a7/_/_/build/6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <stdio.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef fseeko
  return ((int*)(&fseeko))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the aligned_alloc exist failed with the following output:
Change Dir: C:/Users/jrandolp/.conan/data/coda-oss/CMake_ae1a9d6d2c0f50a7/_/_/build/6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/MSBuild/15.0/Bin/MSBuild.exe cmTC_14176.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=15.0 /v:m
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework^M
Copyright (C) Microsoft Corporation. All rights reserved.^M
^M
  Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27027.1 for x64^M
  Copyright (C) Microsoft Corporation.  All rights reserved.^M
  ^M
  cl /c /Zi /W1 /WX- /diagnostics:classic /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_14176.dir\Debug\\" /Fd"cmTC_14176.dir\Debug\vc141.pdb" /Gd /TC /errorReport:queue "C:\Users\jrandolp\.conan\data\coda-oss\CMake_ae1a9d6d2c0f50a7\_\_\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\CMakeFiles\CMakeTmp\CheckSymbolExists.c"^M
  CheckSymbolExists.c^M
  ^M
C:\Users\jrandolp\.conan\data\coda-oss\CMake_ae1a9d6d2c0f50a7\_\_\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\CMakeFiles\CMakeTmp\CheckSymbolExists.c(8): error C2065: 'aligned_alloc': undeclared identifier [C:\Users\jrandolp\.conan\data\coda-oss\CMake_ae1a9d6d2c0f50a7\_\_\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\CMakeFiles\CMakeTmp\cmTC_14176.vcxproj]^M

File C:/Users/jrandolp/.conan/data/coda-oss/CMake_ae1a9d6d2c0f50a7/_/_/build/6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <malloc.h>

```

**Comment by kdwilhelm** [comment]
During the configure step, CMake runs a series of tests to find if libraries, headers, and functions are available by trying to compile a small stub which should succeed if the thing it is looking for is available or fail otherwise. It logs all the results to `CMakeFiles/CMakeError.log` in the build directory. The error messages above all show up there for me after a successful Windows build.

I think the issue could be the build type, which appears to be Debug. One issue on Windows is that building a Debug version of a Python extension requires debug versions of the Python libraries to be installed (the extension is linked with `/MDd`, so the Python installation must be as well). This is not supported by Anaconda, and requires some non-default settings to be enabled when installing python using the python.org installer. Without having those, the build should give an error like `LINK : fatal error LNK1104: cannot open file 'python37_d.lib'`

Could you try building with Release or RelWithDebInfo? Those build types link with the release version of the runtime libraries. You can do this by passing `-s build_type=Release` at the end of your conan create command. You can also change the default build_type in `~/.conan/profiles/default`

**Comment by jmrandol** [comment]
I will try doing in release mode.  Note that I did disable python in this instance.

**Comment by jmrandol** [comment]
Same error.  Conan output is:
```

coda-oss/CMake_ae1a9d6d2c0f50a7: ERROR: Package '6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7' build failed
coda-oss/CMake_ae1a9d6d2c0f50a7: WARN: Build folder C:\Users\jrandolp\.conan\data\coda-oss\CMake_ae1a9d6d2c0f50a7\_\_\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7
ERROR: coda-oss/CMake_ae1a9d6d2c0f50a7: Error in build() method, line 57
        cmake.build()
        ConanException: Error 1 while executing cmake --build C:\Users\jrandolp\.conan\data\coda-oss\CMake_ae1a9d6d2c0f50a7\_\_\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7 --config Release -- /m:8 /verbosity:minimal
```

And then CMakeError.log says:


```
Performing C++ SOURCE FILE Test HAVE_ATTRIBUTE_NOINLINE failed with the following output:
Change Dir: C:/Users/jrandolp/.conan/data/coda-oss/CMake_ae1a9d6d2c0f50a7/_/_/build/6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/MSBuild/15.0/Bin/MSBuild.exe cmTC_4a097.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=15.0 /v:m 
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework

Copyright (C) Microsoft Corporation. All rights reserved.



  Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27027.1 for x64

  Copyright (C) Microsoft Corporation.  All rights reserved.

  

  cl /c /Zi /W1 /WX- /diagnostics:classic /Od /Ob0 /D WIN32 /D _WINDOWS /D HAVE_ATTRIBUTE_NOINLINE /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_4a097.dir\Debug\\" /Fd"cmTC_4a097.dir\Debug\vc141.pdb" /Gd /TP /errorReport:queue "C:\Users\jrandolp\.conan\data\coda-oss\CMake_ae1a9d6d2c0f50a7\_\_\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\CMakeFiles\CMakeTmp\src.cxx"

  src.cxx

  

C:\Users\jrandolp\.conan\data\coda-oss\CMake_ae1a9d6d2c0f50a7\_\_\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\CMakeFiles\CMakeTmp\src.cxx(1): error C2065: 'noinline': undeclared identifier [C:\Users\jrandolp\.conan\data\coda-oss\CMake_ae1a9d6d2c0f50a7\_\_\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\CMakeFiles\CMakeTmp\cmTC_4a097.vcxproj]

C:\Users\jrandolp\.conan\data\coda-oss\CMake_ae1a9d6d2c0f50a7\_\_\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\CMakeFiles\CMakeTmp\src.cxx(1): error C2146: syntax error: missing ';' before identifier 'fn' [C:\Users\jrandolp\.conan\data\coda-oss\CMake_ae1a9d6d2c0f50a7\_\_\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\CMakeFiles\CMakeTmp\cmTC_4a097.vcxproj]

C:\Users\jrandolp\.conan\data\coda-oss\CMake_ae1a9d6d2c0f50a7\_\_\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\CMakeFiles\CMakeTmp\src.cxx(1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [C:\Users\jrandolp\.conan\data\coda-oss\CMake_ae1a9d6d2c0f50a7\_\_\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\CMakeFiles\CMakeTmp\cmTC_4a097.vcxproj]


Source file was:
int __attribute__((noinline)) fn() { return 0; } int main() { return fn(); }
Performing C++ SOURCE FILE Test HAVE_ATTRIBUTE_ALIGNED failed with the following output:
Change Dir: C:/Users/jrandolp/.conan/data/coda-oss/CMake_ae1a9d6d2c0f50a7/_/_/build/6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/MSBuild/15.0/Bin/MSBuild.exe cmTC_e7567.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=15.0 /v:m 
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework

Copyright (C) Microsoft Corporation. All rights reserved.



  Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27027.1 for x64

  Copyright (C) Microsoft Corporation.  All rights reserved.

  

  cl /c /Zi /W1 /WX- /diagnostics:classic /Od /Ob0 /D WIN32 /D _WINDOWS /D HAVE_ATTRIBUTE_ALIGNED /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_e7567.dir\Debug\\" /Fd"cmTC_e7567.dir\Debug\vc141.pdb" /Gd /TP /errorReport:queue "C:\Users\jrandolp\.conan\data\coda-oss\CMake_ae1a9d6d2c0f50a7\_\_\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\CMakeFiles\CMakeTmp\src.cxx"

  src.cxx

  

C:\Users\jrandolp\.conan\data\coda-oss\CMake_ae1a9d6d2c0f50a7\_\_\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\CMakeFiles\CMakeTmp\src.cxx(1): error C2146: syntax error: missing ';' before identifier '__attribute__' [C:\Users\jrandolp\.conan\data\coda-oss\CMake_ae1a9d6d2c0f50a7\_\_\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\CMakeFiles\CMakeTmp\cmTC_e7567.vcxproj]

C:\Users\jrandolp\.conan\data\coda-oss\CMake_ae1a9d6d2c0f50a7\_\_\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\CMakeFiles\CMakeTmp\src.cxx(1): error C3861: 'aligned': identifier not found [C:\Users\jrandolp\.conan\data\coda-oss\CMake_ae1a9d6d2c0f50a7\_\_\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\CMakeFiles\CMakeTmp\cmTC_e7567.vcxproj]

C:\Users\jrandolp\.conan\data\coda-oss\CMake_ae1a9d6d2c0f50a7\_\_\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\CMakeFiles\CMakeTmp\src.cxx(1): error C3861: '__attribute__': identifier not found [C:\Users\jrandolp\.conan\data\coda-oss\CMake_ae1a9d6d2c0f50a7\_\_\build\6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\CMakeFiles\CMakeTmp\cmTC_e7567.vcxproj]


Source file was:
int main() { int var __attribute__((aligned (32))); return var; }

```

**Comment by kdwilhelm** [comment]
From the file paths it looks like Conan is building directly in its cache and not using the Windows short_paths workaround. This results the Visual Studio build tool failing due to having paths that are too long. Unfortunately the error it gives is buried in a lot of noise in the terminal output, several hundred lines from the bottom, and does not appear in any of the CMake logs:
`
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(321,5): error MSB3491: Could not write lines to file "mt_work_sharing_balanced_runnable_1d_test.dir\Release\mt_work_.216E6F81.tlog\mt_work_sharing_balanced_runnable_1d_test.lastbuildstate". The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.`

Can you check the `user_home_short` and `use_always_short_paths` settings? https://github.com/mdaus/coda-oss/pull/269#issuecomment-618650662

Maybe also try manually removing the old directory from the cache (`C:\Users\jrandolp\.conan\data\coda-oss\CMake_ae1a9d6d2c0f50a7`) and make sure you have write access for the directory set in `user_home_short` (the default is `C:\.conan`, which requires local admin to create on my machine).

**Comment by jmrandol** [comment]
I was able to build with the short path settings and upload to artifactory.

**Comment by jmrandol** [comment]
Can we default the user_home_short  to `~/.conan_local` or `~/.conanshort`?

**Pull request merged**
